// Generated by scripts/generate-ascii.ts
// Do not edit by hand; regenerate with `bun run ascii:generate`.

export const HEADER_BANNER = ` |_ _|_  _  ._ ._ _  
 |_) |_ (/_ |  | | | `;
export const SPLASH_BANNER = `    __    __                    
   / /_  / /____  _________ ___ 
  / __ \\/ __/ _ \\/ ___/ __ \`__ \\
 / /_/ / /_/  __/ /  / / / / / /
/_.___/\\__/\\___/_/  /_/ /_/ /_/ `;
export const FALLBACK_WORDMARK = "BIBLETERM";
export const HEADER_MIN_WIDTH = 96;
export const HEADER_MIN_HEIGHT = 28;
export const SPLASH_MIN_WIDTH = 100;
export const SPLASH_MIN_HEIGHT = 30;

export function renderHeaderBanner(width: number, height: number): string {
  if (width >= HEADER_MIN_WIDTH && height >= HEADER_MIN_HEIGHT) {
    return HEADER_BANNER;
  }

  return FALLBACK_WORDMARK;
}

export function renderSplashBanner(width: number, height: number): string {
  if (width >= SPLASH_MIN_WIDTH && height >= SPLASH_MIN_HEIGHT) {
    return SPLASH_BANNER;
  }

  return FALLBACK_WORDMARK;
}

export function shouldShowSplash(
  width: number,
  height: number,
  env: NodeJS.ProcessEnv = process.env
): boolean {
  if (env.BTERM_NO_SPLASH === "1") {
    return false;
  }

  return width >= SPLASH_MIN_WIDTH && height >= SPLASH_MIN_HEIGHT;
}
