#!/usr/bin/env bun

import { writeFileSync } from "fs";
import { join, resolve } from "path";

const PROJECT_ROOT = resolve(import.meta.dirname || "", "..");
const OUTPUT_PATH = join(PROJECT_ROOT, "src", "ui", "ascii.ts");

function runFiglet(font: string): string {
  const result = Bun.spawnSync(["bunx", "figlet", "-f", font, "bterm"], {
    stderr: "pipe",
    stdout: "pipe",
  });

  if (result.exitCode !== 0) {
    const stderr = Buffer.from(result.stderr).toString("utf8").trim();
    throw new Error(stderr || `figlet generation failed for font ${font}`);
  }

  const raw = Buffer.from(result.stdout).toString("utf8");
  const lines = raw.split("\n");

  while (lines.length > 0 && lines[0].trim().length === 0) {
    lines.shift();
  }

  while (lines.length > 0 && lines[lines.length - 1].trim().length === 0) {
    lines.pop();
  }

  return lines.join("\n");
}

function toTemplateLiteral(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/`/g, "\\`");
}

function main(): void {
  const header = runFiglet("Mini");
  const splash = runFiglet("Slant");
  const source = `// Generated by scripts/generate-ascii.ts
// Do not edit by hand; regenerate with \`bun run ascii:generate\`.

export const HEADER_BANNER = \`${toTemplateLiteral(header)}\`;
export const SPLASH_BANNER = \`${toTemplateLiteral(splash)}\`;
export const FALLBACK_WORDMARK = "BIBLETERM";
export const HEADER_MIN_WIDTH = 96;
export const HEADER_MIN_HEIGHT = 28;
export const SPLASH_MIN_WIDTH = 100;
export const SPLASH_MIN_HEIGHT = 30;

export function renderHeaderBanner(width: number, height: number): string {
  if (width >= HEADER_MIN_WIDTH && height >= HEADER_MIN_HEIGHT) {
    return HEADER_BANNER;
  }

  return FALLBACK_WORDMARK;
}

export function renderSplashBanner(width: number, height: number): string {
  if (width >= SPLASH_MIN_WIDTH && height >= SPLASH_MIN_HEIGHT) {
    return SPLASH_BANNER;
  }

  return FALLBACK_WORDMARK;
}

export function shouldShowSplash(
  width: number,
  height: number,
  env: NodeJS.ProcessEnv = process.env
): boolean {
  if (env.BTERM_NO_SPLASH === "1") {
    return false;
  }

  return width >= SPLASH_MIN_WIDTH && height >= SPLASH_MIN_HEIGHT;
}
`;

  writeFileSync(OUTPUT_PATH, source, "utf8");
  console.log(`Generated ASCII branding: ${OUTPUT_PATH}`);
}

main();
